spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/plus
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PW}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  mail:
    host: smtp.gmail.com
    port: 587
    username: derset0527@gmail.com
    password: kuwpdllzdodmdqvx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 300000 # 5 * 60 * 1000 == 5분

redis:
  host: localhost
  port: 6379

jwt:
  secret: ${JWT_SECRET_KEY}
